### ISSUE TITLE
Why vendors are included ?

### ISSUE THREAD

**Issue by tabbi89** [tsurowiec/translations_from_gdrive#1]

**Comment by tsurowiec** [comment]
Repository is used to build a working docker image.

**Comment by tabbi89** [comment]
Storing vendor is a bad habit. You have got composer and docker image does not have composer installed.

What I would do is to add composer and add to README two methods :) first to install dependencies and second with command to translate.

**Comment by tsurowiec** [comment]
you are right - I had no idea how to run composer during the build of an image - turns out to be trivial. Update coming :)

no need for second method - the image will have all the dependencies already added (by composer this time)

**Comment by tsurowiec** [comment]
vendors removed from repository - now composer runs during image build
